name: release.yml
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. 1.0.0)"
        required: true

permissions:
  contents: write
  packages: write
  checks: read

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build and Release Project

    env:
      BRANCH_NAME: test-release/${{ github.run_id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node and pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

      - name: Create test branch
        run: git checkout -b $BRANCH_NAME

      - name: Set Composer version
        run: |
          jq --arg version "${{ github.event.inputs.tag }}" '.version = $version' composer.json > composer.tmp.json
          mv composer.tmp.json composer.json

      - name: Run build
        run: pnpm build

      - name: Force dist folder and update tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist -f
          git commit -m "Add dist for release ${{ github.event.inputs.tag }}"
          git tag -f ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }} --force
